stages:
  - build
  - pack

build:
  stage: build
  script:
    - ".\\buildAll.ps1"
  artifacts:
    paths:
      - "dnSpy\\dnSpy\\bin\\Release"
    expire_in: 1h

pack:
  stage: pack
  # only:
  #   - master
  script:
    - ".\\pack.ps1"
